spring:
  datasource-staging:
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/fam?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password:
    hikari:
      connection-timeout: 10000
      idle-timeout: 10000
      max-lifetime: 20000
      maximum-pool-size: 50
      pool-name: hikari-detail

  second-datasource-staging:
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/fam_sum?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password:
    hikari:
      connection-timeout: 10000
      idle-timeout: 10000
      max-lifetime: 20000
      maximum-pool-size: 50
      pool-name: hikari-summary




